# Generated by Django 5.0.6 on 2024-12-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
