# Generated by Django 5.0.6 on 2024-10-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TUTOR', 'Tutor'), ('NEW', 'New')], default='ADMIN', max_length=50),
        ),
    ]
