# Generated by Django 5.0.6 on 2024-06-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
    ]
