# Generated by Django 5.0.6 on 2024-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='reupload',
            field=models.BooleanField(default=False),
        ),
    ]
