# Generated by Django 5.0.6 on 2024-07-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_certification_reupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
