# Generated by Django 5.0.6 on 2024-07-01 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
