from django.urls import path
from .views import (
    TutorListView,
    StudentListView,
    UserUpdateView,
    SubjectListView,
    CertificationListView,
    CancelledTimeSlotListView,
    RefundView,
    UpdateTimeSlotView,
)

urlpatterns = [
    path(
        "tutor-list/",
        TutorListView.as_view(),
        name="tutor-list-update",
    ),
    path(
        "tutor/approval/",
        TutorListView.as_view(),
        name="tutor-list-approval",
    ),
    path(
        "student-list/",
        StudentListView.as_view(),
        name="student-list-update",
    ),
    path(
        "update-user/<id>",
        UserUpdateView.as_view(),
        name="student-list-update-id",
    ),
    path(
        "subjects/<user_id>",
        SubjectListView.as_view(),
        name="subject-list",
    ),
    path(
        "certificates/<user_id>",
        CertificationListView.as_view(),
        name="certificate-list",
    ),
    path(
        "cancelled_timeslots/",
        CancelledTimeSlotListView.as_view(),
        name="cancellation-list",
    ),
    path(
        "refund/",
        RefundView.as_view(),
        name="refund",
    ),
    path(
        "updateTimeslot/<id>",
        UpdateTimeSlotView.as_view(),
        name="update-timeslot",
    ),
]
