# Generated by Django 5.0.6 on 2024-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_razorpaytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaytransaction',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
