# Generated by Django 5.0.6 on 2024-09-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_alter_razorpaytransaction_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RazorPayTransaction',
        ),
    ]
