# Generated by Django 5.0.6 on 2024-06-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordates',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
