# Generated by Django 5.0.6 on 2024-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0002_tutordates_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutordates',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
