# Generated by Django 5.0.6 on 2024-12-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0003_timeslots_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('ONGOING', 'Ongoing')], default='AVAILABLE', max_length=100),
        ),
    ]
